# Generated by Django 4.1.3 on 2023-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexcursiones', '0003_viajes_imagen_viaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='imagviajes'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='imagviajes'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='imagviajes'),
        ),
        migrations.AddField(
            model_name='recreadores',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='imagviajes'),
        ),
    ]
