# Generated by Django 4.1.3 on 2023-10-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexcursiones', '0004_clientes_imagen_viaj_documentacion_imagen_viaj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='recreadores',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
