# Generated by Django 4.1.3 on 2023-10-22 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appexcursiones', '0005_alter_clientes_imagen_viaj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacion',
            name='info_documentacion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='recreadores',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='imagen_viaj',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
