# Generated by Django 4.1.3 on 2023-10-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexcursiones', '0006_documentacion_info_documentacion_alter_avatar_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentacion',
            old_name='info_documentacion',
            new_name='info_document',
        ),
    ]
